// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "x-aui-user-id": "x-aui-user-id",
 *         "x-aui-source": "x-aui-source",
 *         "x-aui-organization-id": "x-aui-organization-id",
 *         agent_id: "agent_id",
 *         interaction_id: "interaction_id",
 *         text: "text"
 *     }
 */
export interface RerunMessageRequest {
    "x-aui-user-id"?: string;
    "x-aui-source"?: string;
    "x-aui-organization-id"?: string;
    agent_id: string;
    interaction_id: string;
    text: string;
    /** Signed image URL on the replayed message. */
    image_url?: string;
    version_id?: string;
    version_tag?: string;
}
