// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Apollo from "../../../index.js";

export declare namespace Channels {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Channels {
    protected readonly _options: Channels.Options;

    constructor(_options: Channels.Options = {}) {
        this._options = _options;
    }

    /**
     * Send the opener on ``channel`` and bind the recipient's phone to a thread.
     * Omit ``thread_id`` to start a new thread (its id is returned); pass it to
     * continue an existing one. Template fields apply to WhatsApp only.
     *
     * @param {string} channel - Channel id: 'whatsapp' or 'sms'.
     * @param {Apollo.InitiateThreadRequest} request
     * @param {Channels.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.channels.initiateThread("channel", {
     *         "x-aui-organization-id": "x-aui-organization-id",
     *         "x-aui-user-id": "x-aui-user-id",
     *         "x-aui-source": "x-aui-source",
     *         "x-aui-network-id": "x-aui-network-id",
     *         "x-aui-account-id": "x-aui-account-id",
     *         "x-aui-network-category-id": "x-aui-network-category-id",
     *         phone_number: "phone_number",
     *         agent_id: "agent_id"
     *     })
     */
    public initiateThread(
        channel: string,
        request: Apollo.InitiateThreadRequest,
        requestOptions?: Channels.RequestOptions,
    ): core.HttpResponsePromise<Apollo.InitiateThreadResponse> {
        return core.HttpResponsePromise.fromPromise(this.__initiateThread(channel, request, requestOptions));
    }

    private async __initiateThread(
        channel: string,
        request: Apollo.InitiateThreadRequest,
        requestOptions?: Channels.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.InitiateThreadResponse>> {
        const {
            "x-aui-organization-id": auiOrganizationId,
            "x-aui-user-id": auiUserId,
            "x-aui-source": auiSource,
            "x-aui-network-id": auiNetworkId,
            "x-aui-account-id": auiAccountId,
            "x-aui-network-category-id": auiNetworkCategoryId,
            ..._body
        } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-aui-organization-id": auiOrganizationId != null ? auiOrganizationId : undefined,
                "x-aui-user-id": auiUserId != null ? auiUserId : undefined,
                "x-aui-source": auiSource != null ? auiSource : undefined,
                "x-aui-network-id": auiNetworkId != null ? auiNetworkId : undefined,
                "x-aui-account-id": auiAccountId != null ? auiAccountId : undefined,
                "x-aui-network-category-id": auiNetworkCategoryId != null ? auiNetworkCategoryId : undefined,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `messaging/v1/channels/${core.url.encodePathParam(channel)}/threads`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.InitiateThreadResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling POST /messaging/v1/channels/{channel}/threads.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
