// This file was auto-generated by Fern from our API Definition.

export class ApolloTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, ApolloTimeoutError.prototype);
    }
}
