// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "x-aui-organization-id": "x-aui-organization-id",
 *         "x-aui-user-id": "x-aui-user-id",
 *         "x-aui-source": "x-aui-source",
 *         "x-aui-network-id": "x-aui-network-id",
 *         "x-aui-account-id": "x-aui-account-id",
 *         "x-aui-network-category-id": "x-aui-network-category-id"
 *     }
 */
export interface DeleteAgentRequest {
    "x-aui-organization-id"?: string;
    "x-aui-user-id"?: string;
    "x-aui-source"?: string;
    "x-aui-network-id"?: string;
    "x-aui-account-id"?: string;
    "x-aui-network-category-id"?: string;
}
