// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "x-aui-end-user-id": "x-aui-end-user-id",
 *         "x-aui-end-user-data": "x-aui-end-user-data",
 *         body: {
 *             "grant_type": "publishable_key",
 *             "publishable_key": "pk_network_..."
 *         }
 *     }
 */
export interface IssueTokenRequest {
    "x-aui-end-user-id"?: string;
    "x-aui-end-user-data"?: string;
    body: Record<string, unknown>;
}
