// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../../../../index.js";

/**
 * @example
 *     {
 *         "x-aui-organization-id": "x-aui-organization-id",
 *         "x-aui-user-id": "x-aui-user-id",
 *         "x-aui-source": "x-aui-source",
 *         "x-aui-network-id": "x-aui-network-id",
 *         "x-aui-account-id": "x-aui-account-id",
 *         "x-aui-network-category-id": "x-aui-network-category-id",
 *         "page[size]": 1,
 *         "page[after]": "page[after]",
 *         "page[before]": "page[before]",
 *         sort_by: "sort_by",
 *         sort_order: "asc"
 *     }
 */
export interface ListProjectsRequest {
    "page[size]"?: number;
    "page[after]"?: string;
    "page[before]"?: string;
    sort_by?: string;
    sort_order?: Apollo.ListProjectsRequestSortOrder;
    "x-aui-organization-id"?: string;
    "x-aui-user-id"?: string;
    "x-aui-source"?: string;
    "x-aui-network-id"?: string;
    "x-aui-account-id"?: string;
    "x-aui-network-category-id"?: string;
}
