// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface CardParameter {
    param: string;
    title: string;
    value?: unknown;
    type: Apollo.ParameterType;
}
