// This file was auto-generated by Fern from our API Definition.

export interface ContactParty {
    id: string;
    type: string;
    email?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
