// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Error frame (type = "error"); connection closes afterwards.
 */
export interface ErrorEnvelope {
    seq: number;
    type: "error";
    data: Apollo.ErrorMessagePayload;
}
