// This file was auto-generated by Fern from our API Definition.

/**
 * Error payload carried inside the error envelope's `data`. apollo-api sends
 * a single `error` string (e.g. validation failures). Connection closes
 * afterwards (close code 1008 for auth/app errors, 1011 for server errors).
 */
export interface ErrorMessagePayload {
    error: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
