// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Final complete message frame (type = "message").
 */
export interface FinalMessageEnvelope {
    seq: number;
    type: "message";
    data: Apollo.FinalMessagePayload;
}
