// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface ListTasksResponse {
    tasks?: Apollo.CreateTaskResponse[];
    total: number;
    page: number;
    size: number;
}
