// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface MessageContactParty {
    id: string;
    type: Apollo.Actor;
    email?: string;
}
