// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Agent reply in external API shape (used by both WS and REST).
 */
export interface Message {
    id: string;
    created_at: string;
    text: string;
    sender: Apollo.ContactParty;
    receiver: Apollo.ContactParty;
    cards?: Apollo.Card[];
    welcome_message?: string;
    followup_suggestions?: string[];
    url?: string;
    input_tokens?: number;
    output_tokens?: number;
    trace_info?: Record<string, unknown>;
    /** Accepts any additional properties */
    [key: string]: any;
}
