// This file was auto-generated by Fern from our API Definition.

export interface PresignedUploadResponse {
    /** Signed GET URL for the uploaded object; pass as image_url on POST /messages. */
    image_url: string;
    upload_url: string;
    /** Content-Type header required on the PUT upload (must match exactly). */
    content_type: string;
}
