// This file was auto-generated by Fern from our API Definition.

export interface ProductParameter {
    /** Parameter name */
    title: string;
    /** Parameter value (can be string, number, array, or object) */
    value: ProductParameter.Value;
    type: ProductParameter.Type;
}

export namespace ProductParameter {
    /**
     * Parameter value (can be string, number, array, or object)
     */
    export type Value = string | number | unknown[] | Record<string, unknown>;
    export const Type = {
        String: "string",
        Numeric: "numeric",
        Array: "array",
        Object: "object",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
