// This file was auto-generated by Fern from our API Definition.

export const ScopeEntityType = {
    Normal: "normal",
    UserProfile: "user-profile",
    UserProvided: "user-provided",
} as const;
export type ScopeEntityType = (typeof ScopeEntityType)[keyof typeof ScopeEntityType];
