// This file was auto-generated by Fern from our API Definition.

export const SimpleViewMethod = {
    EntityParamReferenced: "entity_param_referenced",
    EntityParam: "entity_param",
    ParamValue: "param_value",
    ParamExtractedCurrent: "param_extracted_current",
    UserQuestion: "user_question",
    ConversationStarted: "conversation_started",
    ParamMissing: "param_missing",
    UserProfileParam: "user_profile_param",
    CurrentUrl: "current_url",
    ApiRequestParamValue: "api_request_param_value",
    ApiResponseParamValue: "api_response_param_value",
    EntityMissing: "entity_missing",
    ToolParamsFilled: "tool_params_filled",
    ToolRequiredParamsFilled: "tool_required_params_filled",
    ToolOptionalParamsFilled: "tool_optional_params_filled",
} as const;
export type SimpleViewMethod = (typeof SimpleViewMethod)[keyof typeof SimpleViewMethod];
