// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Streaming text update frame (type = "event").
 */
export interface StreamingUpdateEnvelope {
    seq: number;
    type: "event";
    data: Apollo.StreamingUpdatePayload;
}
