// This file was auto-generated by Fern from our API Definition.

export interface TaskListItemSchema {
    id: string;
    title?: string;
    created_at?: string;
    created_by?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
