// This file was auto-generated by Fern from our API Definition.

/**
 * RFC 6749 §5.1 successful token response.
 *
 * Extended with the network's ``agent_id``. RFC 6749 §5.1 permits additional
 * response parameters, so it rides alongside the standard token fields.
 * ``agent_id`` is resolved from agent-settings by ``network_id`` and is
 * ``None`` when the network has no agent (or the PK is not network-scoped).
 */
export interface TokenResponse {
    access_token: string;
    token_type?: string;
    expires_in: number;
    agent_id?: string;
    organization_id?: string;
}
