// This file was auto-generated by Fern from our API Definition.

/**
 * Schema: message (required), channel (optional).
 */
export interface TraceInput {
    message: string;
    channel?: TraceInput.Channel;
}

export namespace TraceInput {
    export const Channel = {
        Websocket: "WEBSOCKET",
        Rest: "REST",
        Webhook: "WEBHOOK",
    } as const;
    export type Channel = (typeof Channel)[keyof typeof Channel];
}
