// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceIntegration {
    code: string;
    type: Apollo.TraceIntegrationType;
    requests: Apollo.TraceIntegrationRequest[];
    response?: unknown;
    status_code?: number;
    error_message?: string;
}
