// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceDecisionParamsCheck {
    type?: Apollo.TraceDecisionType;
    tool: string;
    status: Apollo.TraceParamsCheckStatus;
    missing?: string[];
    track_id?: string;
}
