// This file was auto-generated by Fern from our API Definition.

export interface TraceReferencedEntity {
    entity: string;
    id?: string;
    reference?: string;
    is_visible: boolean;
    track_id: string;
}
