// This file was auto-generated by Fern from our API Definition.

/**
 * A rendered JSX card included in the workflow response.
 */
export interface TraceJsxWidget {
    name: string;
    category: string;
    rendered_jsx: string;
    is_recommended?: boolean;
    index?: number;
}
