// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceDecisionRuleTriggered {
    type?: Apollo.TraceDecisionType;
    tool: string;
    rule: Apollo.TraceRuleBase;
    track_id?: string;
}
