// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Root trace. Schema: interaction_id, input, understanding, decisions, response (required); session_id, timestamp, context (optional).
 */
export interface TraceInfo {
    interaction_id: string;
    session_id?: string;
    timestamp: string;
    input: Apollo.TraceInput;
    context?: Apollo.TraceContext;
    understanding: Apollo.TraceUnderstanding;
    decisions?: TraceInfo.Decisions.Item[];
    response: Apollo.TraceResponse;
}

export namespace TraceInfo {
    export type Decisions = Decisions.Item[];

    export namespace Decisions {
        export type Item =
            | Apollo.TraceDecisionActivateTool
            | Apollo.TraceDecisionRuleTriggered
            | Apollo.TraceDecisionParamsCheck
            | Apollo.TraceDecisionCallIntegration
            | Apollo.TraceDecisionAskForConfirmation
            | Apollo.TraceDecisionToolTextResponse
            | Apollo.TraceDecisionSelfReview
            | Apollo.TraceDecisionActivateSubTool;
    }
}
