// This file was auto-generated by Fern from our API Definition.

/** Schema: confirmation_yes | confirmation_no | param_answer | topic_change. */
export const TraceFollowupType = {
    ConfirmationYes: "confirmation_yes",
    ConfirmationNo: "confirmation_no",
    ParamAnswer: "param_answer",
    TopicChange: "topic_change",
} as const;
export type TraceFollowupType = (typeof TraceFollowupType)[keyof typeof TraceFollowupType];
