// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceDecisionActivateTool {
    type?: Apollo.TraceDecisionType;
    tool: string;
    trigger: Apollo.TraceTrigger;
    track_id?: string;
    is_fallback?: boolean;
    fallback_origin?: string;
    referenced_entities?: Apollo.TraceReferencedEntity[];
    check_status?: Apollo.WorkflowCheckStatus;
}
