// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceDecisionCallIntegration {
    type?: Apollo.TraceDecisionType;
    tool: string;
    integration: Apollo.TraceIntegration;
    track_id?: string;
}
