// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../../../../index.js";

/**
 * @example
 *     {
 *         filters: {}
 *     }
 */
export interface ListThreadsRequest {
    filters: Apollo.ThreadListFilters;
    "page[size]"?: number;
    "page[after]"?: string;
    "page[before]"?: string;
    sort_by?: string;
    sort_order?: Apollo.ListThreadsRequestSortOrder;
    "x-aui-organization-id"?: string;
    "x-aui-user-id"?: string;
    "x-aui-source"?: string;
    "x-aui-network-id"?: string;
    "x-aui-account-id"?: string;
    "x-aui-network-category-id"?: string;
}
