// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Apollo from "../../../index.js";

export declare namespace ControllerApi {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ControllerApi {
    protected readonly _options: ControllerApi.Options;

    constructor(_options: ControllerApi.Options = {}) {
        this._options = _options;
    }

    /**
     * Exchange a credential for a short-lived access token. Supported grant types: `publishable_key`. Refresh and other grants will be added on the same endpoint.
     *
     * @param {Apollo.IssueTokenRequestBody} request
     * @param {ControllerApi.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.BadGatewayError}
     *
     * @example
     *     await client.controllerApi.issueToken({
     *         "x-aui-end-user-id": "x-aui-end-user-id",
     *         "x-aui-end-user-data": "x-aui-end-user-data",
     *         grant_type: "publishable_key",
     *         publishable_key: "pk_network_..."
     *     })
     */
    public issueToken(
        request: Apollo.IssueTokenRequestBody,
        requestOptions?: ControllerApi.RequestOptions,
    ): core.HttpResponsePromise<Apollo.TokenResponse> {
        return core.HttpResponsePromise.fromPromise(this.__issueToken(request, requestOptions));
    }

    private async __issueToken(
        request: Apollo.IssueTokenRequestBody,
        requestOptions?: ControllerApi.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.TokenResponse>> {
        const { "x-aui-end-user-id": auiEndUserId, "x-aui-end-user-data": auiEndUserData, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-aui-end-user-id": auiEndUserId != null ? auiEndUserId : undefined,
                "x-aui-end-user-data": auiEndUserData != null ? auiEndUserData : undefined,
                "x-aui-organization-id": requestOptions?.auiOrganizationId ?? this._options?.auiOrganizationId,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                "v1/management/auth/token",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.TokenResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(
                        _response.error.body as Apollo.HttpValidationError,
                        _response.rawResponse,
                    );
                case 502:
                    throw new Apollo.BadGatewayError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError("Timeout exceeded when calling POST /v1/management/auth/token.");
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Apollo.ControllerApiListUserTasksRequest} request
     * @param {ControllerApi.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.UnprocessableEntityError}
     *
     * @example
     *     await client.controllerApi.listUserTasks({
     *         organization_id: "organization_id",
     *         user_id: "user_id",
     *         account_id: "account_id",
     *         network_id: "network_id",
     *         page: 1,
     *         limit: 1
     *     })
     */
    public listUserTasks(
        request: Apollo.ControllerApiListUserTasksRequest,
        requestOptions?: ControllerApi.RequestOptions,
    ): core.HttpResponsePromise<Apollo.ListTasksResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listUserTasks(request, requestOptions));
    }

    private async __listUserTasks(
        request: Apollo.ControllerApiListUserTasksRequest,
        requestOptions?: ControllerApi.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.ListTasksResponse>> {
        const {
            organization_id: organizationId,
            user_id: userId,
            account_id: accountId,
            network_id: networkId,
            page,
            limit,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.organization_id = organizationId;
        if (userId != null) {
            _queryParams.user_id = userId;
        }

        if (accountId != null) {
            _queryParams.account_id = accountId;
        }

        if (networkId != null) {
            _queryParams.network_id = networkId;
        }

        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-aui-organization-id": requestOptions?.auiOrganizationId ?? this._options?.auiOrganizationId,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                "v1/messaging/tasks",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.ListTasksResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Apollo.UnprocessableEntityError(
                        _response.error.body as Apollo.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError("Timeout exceeded when calling GET /v1/messaging/tasks.");
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates a task for ``data.agent_id``: Apollo resolves the network (and active
     * version) from agent-settings and runs task creation inside intelligent-agent.
     *
     * The trust boundary is ``require_organization_id`` (gateway/token) plus a check
     * that the agent's organization matches it — the network scope dependency is no
     * longer used here.
     *
     * @param {Apollo.CreateTaskRequest} request
     * @param {ControllerApi.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.UnprocessableEntityError}
     *
     * @example
     *     await client.controllerApi.createTask({
     *         "x-aui-user-id": "x-aui-user-id",
     *         "x-aui-source": "x-aui-source",
     *         agent_id: "agent_id",
     *         user_id: "user_id",
     *         task_origin_type: "task_origin_type"
     *     })
     */
    public createTask(
        request: Apollo.CreateTaskRequest,
        requestOptions?: ControllerApi.RequestOptions,
    ): core.HttpResponsePromise<Apollo.CreateTaskResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createTask(request, requestOptions));
    }

    private async __createTask(
        request: Apollo.CreateTaskRequest,
        requestOptions?: ControllerApi.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.CreateTaskResponse>> {
        const { "x-aui-user-id": auiUserId, "x-aui-source": auiSource, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-aui-user-id": auiUserId != null ? auiUserId : undefined,
                "x-aui-source": auiSource != null ? auiSource : undefined,
                "x-aui-organization-id": requestOptions?.auiOrganizationId ?? this._options?.auiOrganizationId,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                "v1/messaging/tasks",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.CreateTaskResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Apollo.UnprocessableEntityError(
                        _response.error.body as Apollo.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError("Timeout exceeded when calling POST /v1/messaging/tasks.");
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} taskId
     * @param {ControllerApi.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.UnprocessableEntityError}
     *
     * @example
     *     await client.controllerApi.getTaskMessages("task_id")
     */
    public getTaskMessages(
        taskId: string,
        requestOptions?: ControllerApi.RequestOptions,
    ): core.HttpResponsePromise<unknown[]> {
        return core.HttpResponsePromise.fromPromise(this.__getTaskMessages(taskId, requestOptions));
    }

    private async __getTaskMessages(
        taskId: string,
        requestOptions?: ControllerApi.RequestOptions,
    ): Promise<core.WithRawResponse<unknown[]>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-aui-organization-id": requestOptions?.auiOrganizationId ?? this._options?.auiOrganizationId,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `v1/messaging/tasks/${core.url.encodePathParam(taskId)}/messages`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as unknown[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Apollo.UnprocessableEntityError(
                        _response.error.body as Apollo.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /v1/messaging/tasks/{task_id}/messages.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Mirrors IA's external trace-info endpoint.
     *
     * The IA call is scoped only by ``task_id`` + ``interaction_id`` (the service
     * ignores network scope); org-id is enforced by the router-level
     * ``require_organization_id`` gate.
     *
     * @param {string} taskId
     * @param {string} interactionId
     * @param {ControllerApi.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.UnprocessableEntityError}
     *
     * @example
     *     await client.controllerApi.getTraceInfo("task_id", "interaction_id")
     */
    public getTraceInfo(
        taskId: string,
        interactionId: string,
        requestOptions?: ControllerApi.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getTraceInfo(taskId, interactionId, requestOptions));
    }

    private async __getTraceInfo(
        taskId: string,
        interactionId: string,
        requestOptions?: ControllerApi.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-aui-organization-id": requestOptions?.auiOrganizationId ?? this._options?.auiOrganizationId,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `v1/messaging/tasks/${core.url.encodePathParam(taskId)}/interactions/${core.url.encodePathParam(interactionId)}/trace-info`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Apollo.UnprocessableEntityError(
                        _response.error.body as Apollo.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /v1/messaging/tasks/{task_id}/interactions/{interaction_id}/trace-info.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Mirrors IA's task-level trace-info endpoint (all interaction traces).
     *
     * Like the interaction-level route, the IA call is scoped only by ``task_id``;
     * org-id is enforced by the router-level ``require_organization_id`` gate.
     *
     * @param {string} taskId
     * @param {ControllerApi.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.UnprocessableEntityError}
     *
     * @example
     *     await client.controllerApi.getTaskTraceInfo("task_id")
     */
    public getTaskTraceInfo(
        taskId: string,
        requestOptions?: ControllerApi.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>[]> {
        return core.HttpResponsePromise.fromPromise(this.__getTaskTraceInfo(taskId, requestOptions));
    }

    private async __getTaskTraceInfo(
        taskId: string,
        requestOptions?: ControllerApi.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>[]>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-aui-organization-id": requestOptions?.auiOrganizationId ?? this._options?.auiOrganizationId,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `v1/messaging/tasks/${core.url.encodePathParam(taskId)}/trace-info`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Apollo.UnprocessableEntityError(
                        _response.error.body as Apollo.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /v1/messaging/tasks/{task_id}/trace-info.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} taskId
     * @param {ControllerApi.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.UnprocessableEntityError}
     *
     * @example
     *     await client.controllerApi.getTask("task_id")
     */
    public getTask(
        taskId: string,
        requestOptions?: ControllerApi.RequestOptions,
    ): core.HttpResponsePromise<Apollo.CreateTaskResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTask(taskId, requestOptions));
    }

    private async __getTask(
        taskId: string,
        requestOptions?: ControllerApi.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.CreateTaskResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-aui-organization-id": requestOptions?.auiOrganizationId ?? this._options?.auiOrganizationId,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `v1/messaging/tasks/${core.url.encodePathParam(taskId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.CreateTaskResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Apollo.UnprocessableEntityError(
                        _response.error.body as Apollo.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError("Timeout exceeded when calling GET /v1/messaging/tasks/{task_id}.");
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Same behavior as intelligent-agent POST /api/v1/external/message, orchestrated from apollo-api
     * using internal /api/v1/* endpoints (no call to /external/message).
     *
     * @param {Apollo.SubmitMessageRequest} request
     * @param {ControllerApi.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.UnprocessableEntityError}
     *
     * @example
     *     await client.controllerApi.sendMessage({
     *         "x-aui-source": "x-aui-source",
     *         "x-aui-client": "x-aui-client",
     *         include_trace: true,
     *         task_id: "task_id"
     *     })
     */
    public sendMessage(
        request: Apollo.SubmitMessageRequest,
        requestOptions?: ControllerApi.RequestOptions,
    ): core.HttpResponsePromise<Apollo.Message> {
        return core.HttpResponsePromise.fromPromise(this.__sendMessage(request, requestOptions));
    }

    private async __sendMessage(
        request: Apollo.SubmitMessageRequest,
        requestOptions?: ControllerApi.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.Message>> {
        const { include_trace: includeTrace, "x-aui-source": auiSource, "x-aui-client": auiClient, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (includeTrace != null) {
            _queryParams.include_trace = includeTrace.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-aui-source": auiSource != null ? auiSource : undefined,
                "x-aui-client": auiClient != null ? auiClient : undefined,
                "x-aui-organization-id": requestOptions?.auiOrganizationId ?? this._options?.auiOrganizationId,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                "v1/messaging/messages",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.Message, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Apollo.UnprocessableEntityError(
                        _response.error.body as Apollo.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError("Timeout exceeded when calling POST /v1/messaging/messages.");
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Apollo.PresignedUploadRequest} request
     * @param {ControllerApi.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.UnprocessableEntityError}
     *
     * @example
     *     await client.controllerApi.createPresignedUploadUrl({
     *         filename: "filename"
     *     })
     */
    public createPresignedUploadUrl(
        request: Apollo.PresignedUploadRequest,
        requestOptions?: ControllerApi.RequestOptions,
    ): core.HttpResponsePromise<Apollo.PresignedUploadResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createPresignedUploadUrl(request, requestOptions));
    }

    private async __createPresignedUploadUrl(
        request: Apollo.PresignedUploadRequest,
        requestOptions?: ControllerApi.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.PresignedUploadResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-aui-organization-id": requestOptions?.auiOrganizationId ?? this._options?.auiOrganizationId,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                "v1/messaging/uploads/presign",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.PresignedUploadResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Apollo.UnprocessableEntityError(
                        _response.error.body as Apollo.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling POST /v1/messaging/uploads/presign.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Apollo.TextConversationInitiateRequest} request
     * @param {ControllerApi.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.UnprocessableEntityError}
     *
     * @example
     *     await client.controllerApi.startTextConversation({
     *         phoneNumber: "phoneNumber",
     *         agentId: "agentId"
     *     })
     */
    public startTextConversation(
        request: Apollo.TextConversationInitiateRequest,
        requestOptions?: ControllerApi.RequestOptions,
    ): core.HttpResponsePromise<Apollo.TextConversationInitiateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__startTextConversation(request, requestOptions));
    }

    private async __startTextConversation(
        request: Apollo.TextConversationInitiateRequest,
        requestOptions?: ControllerApi.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.TextConversationInitiateResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-aui-organization-id": requestOptions?.auiOrganizationId ?? this._options?.auiOrganizationId,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                "v1/channels/whatsapp/conversations",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Apollo.TextConversationInitiateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Apollo.UnprocessableEntityError(
                        _response.error.body as Apollo.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling POST /v1/channels/whatsapp/conversations.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
