// This file was auto-generated by Fern from our API Definition.

import * as Apollo from "../../src/api/index";
import { ApolloClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ControllerApi", () => {
    test("issueToken (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { grant_type: "publishable_key", publishable_key: "pk_network_..." };
        const rawResponseBody = {
            access_token: "access_token",
            token_type: "token_type",
            expires_in: 1,
            agent_id: "agent_id",
            organization_id: "organization_id",
        };
        server
            .mockEndpoint()
            .post("/v1/management/auth/token")
            .header("x-aui-end-user-id", "x-aui-end-user-id")
            .header("x-aui-end-user-data", "x-aui-end-user-data")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.issueToken({
            "x-aui-end-user-id": "x-aui-end-user-id",
            "x-aui-end-user-data": "x-aui-end-user-data",
            grant_type: "publishable_key",
            publishable_key: "pk_network_...",
        });
        expect(response).toEqual({
            access_token: "access_token",
            token_type: "token_type",
            expires_in: 1,
            agent_id: "agent_id",
            organization_id: "organization_id",
        });
    });

    test("issueToken (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { grant_type: "grant_type", publishable_key: "publishable_key" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/management/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.issueToken({
                grant_type: "grant_type",
                publishable_key: "publishable_key",
            });
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("issueToken (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { grant_type: "grant_type", publishable_key: "publishable_key" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/v1/management/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.issueToken({
                grant_type: "grant_type",
                publishable_key: "publishable_key",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("issueToken (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { grant_type: "grant_type", publishable_key: "publishable_key" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/management/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.issueToken({
                grant_type: "grant_type",
                publishable_key: "publishable_key",
            });
        }).rejects.toThrow(Apollo.BadGatewayError);
    });

    test("listUserTasks (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });

        const rawResponseBody = {
            items: [{ id: "id", title: "title", created_at: "created_at", created_by: "created_by" }],
            total: 1,
            page: 1,
            size: 1,
        };
        server
            .mockEndpoint()
            .get("/v1/messaging/tasks")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.listUserTasks({
            organization_id: "organization_id",
            user_id: "user_id",
            account_id: "account_id",
            network_id: "network_id",
            page: 1,
            limit: 1,
        });
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    title: "title",
                    created_at: "created_at",
                    created_by: "created_by",
                },
            ],
            total: 1,
            page: 1,
            size: 1,
        });
    });

    test("listUserTasks (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/v1/messaging/tasks")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.listUserTasks({
                organization_id: "organization_id",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("createTask (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { agent_id: "agent_id", user_id: "user_id", task_origin_type: "task_origin_type" };
        const rawResponseBody = {
            id: "id",
            user_id: "user_id",
            title: "title",
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
        };
        server
            .mockEndpoint()
            .post("/v1/messaging/tasks")
            .header("x-aui-user-id", "x-aui-user-id")
            .header("x-aui-source", "x-aui-source")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.createTask({
            "x-aui-user-id": "x-aui-user-id",
            "x-aui-source": "x-aui-source",
            agent_id: "agent_id",
            user_id: "user_id",
            task_origin_type: "task_origin_type",
        });
        expect(response).toEqual({
            id: "id",
            user_id: "user_id",
            title: "title",
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
        });
    });

    test("createTask (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { agent_id: "agent_id", user_id: "user_id", task_origin_type: "task_origin_type" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/v1/messaging/tasks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.createTask({
                agent_id: "agent_id",
                user_id: "user_id",
                task_origin_type: "task_origin_type",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("getTaskMessages (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });

        const rawResponseBody = [{ key: "value" }];
        server
            .mockEndpoint()
            .get("/v1/messaging/tasks/task_id/messages")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.getTaskMessages("task_id");
        expect(response).toEqual([
            {
                key: "value",
            },
        ]);
    });

    test("getTaskMessages (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/v1/messaging/tasks/task_id/messages")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.getTaskMessages("task_id");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("getTraceInfo (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/messaging/tasks/task_id/interactions/interaction_id/trace-info")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.getTraceInfo("task_id", "interaction_id");
        expect(response).toEqual({
            key: "value",
        });
    });

    test("getTraceInfo (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/v1/messaging/tasks/task_id/interactions/interaction_id/trace-info")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.getTraceInfo("task_id", "interaction_id");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("getTaskTraceInfo (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });

        const rawResponseBody = [{ key: "value" }];
        server
            .mockEndpoint()
            .get("/v1/messaging/tasks/task_id/trace-info")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.getTaskTraceInfo("task_id");
        expect(response).toEqual([
            {
                key: "value",
            },
        ]);
    });

    test("getTaskTraceInfo (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/v1/messaging/tasks/task_id/trace-info")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.getTaskTraceInfo("task_id");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("getTask (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            user_id: "user_id",
            title: "title",
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
        };
        server
            .mockEndpoint()
            .get("/v1/messaging/tasks/task_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.getTask("task_id");
        expect(response).toEqual({
            id: "id",
            user_id: "user_id",
            title: "title",
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
        });
    });

    test("getTask (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/v1/messaging/tasks/task_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.getTask("task_id");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("sendMessage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { task_id: "task_id" };
        const rawResponseBody = {
            id: "id",
            created_at: "created_at",
            text: "text",
            sender: { id: "id", type: "type", email: "email" },
            receiver: { id: "id", type: "type", email: "email" },
            cards: [{ index: 1, query: { key: "value" }, rendered_jsx: "rendered_jsx" }],
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
            url: "url",
            input_tokens: 1,
            output_tokens: 1,
            trace_info: { key: "value" },
        };
        server
            .mockEndpoint()
            .post("/v1/messaging/messages")
            .header("x-aui-source", "x-aui-source")
            .header("x-aui-client", "x-aui-client")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.sendMessage({
            "x-aui-source": "x-aui-source",
            "x-aui-client": "x-aui-client",
            include_trace: true,
            task_id: "task_id",
        });
        expect(response).toEqual({
            id: "id",
            created_at: "created_at",
            text: "text",
            sender: {
                id: "id",
                type: "type",
                email: "email",
            },
            receiver: {
                id: "id",
                type: "type",
                email: "email",
            },
            cards: [
                {
                    index: 1,
                    query: {
                        key: "value",
                    },
                    rendered_jsx: "rendered_jsx",
                },
            ],
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
            url: "url",
            input_tokens: 1,
            output_tokens: 1,
            trace_info: {
                key: "value",
            },
        });
    });

    test("sendMessage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { task_id: "task_id" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/v1/messaging/messages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.sendMessage({
                task_id: "task_id",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("createPresignedUploadUrl (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { filename: "filename" };
        const rawResponseBody = { image_url: "image_url", upload_url: "upload_url", content_type: "content_type" };
        server
            .mockEndpoint()
            .post("/v1/messaging/uploads/presign")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.createPresignedUploadUrl({
            filename: "filename",
        });
        expect(response).toEqual({
            image_url: "image_url",
            upload_url: "upload_url",
            content_type: "content_type",
        });
    });

    test("createPresignedUploadUrl (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { filename: "x" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/v1/messaging/uploads/presign")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.createPresignedUploadUrl({
                filename: "x",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("startTextConversation (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { phoneNumber: "phoneNumber", agentId: "agentId" };
        const rawResponseBody = { taskId: "taskId", messageSid: "messageSid" };
        server
            .mockEndpoint()
            .post("/v1/channels/whatsapp/conversations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.startTextConversation({
            phoneNumber: "phoneNumber",
            agentId: "agentId",
        });
        expect(response).toEqual({
            taskId: "taskId",
            messageSid: "messageSid",
        });
    });

    test("startTextConversation (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            auiOrganizationId: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl, aws: server.baseUrl },
        });
        const rawRequestBody = { phoneNumber: "phoneNumber", agentId: "agentId" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/v1/channels/whatsapp/conversations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.startTextConversation({
                phoneNumber: "phoneNumber",
                agentId: "agentId",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });
});
