// This file was auto-generated by Fern from our API Definition.
// MANUALLY FIXED: single GCP environment (Azure/AWS deprecated); `gcp` holds the
// WebSocket host used by apolloWsSession (see .fernignore).

export interface ApolloEnvironmentUrls {
    base: string;
    gcp: string;
}

export const ApolloEnvironment = {
    Gcp: {
        base: "https://api-staging-v3.internal-aui.io/apollo-api-v2",
        gcp: "wss://api-staging-v3.internal-aui.io",
    },
} as const;

export type ApolloEnvironment = typeof ApolloEnvironment.Gcp;
