// This file was auto-generated by Fern from our API Definition.
// MANUALLY FIXED: Added wsUrl property for WebSocket URL resolution (see .fernignore)

export interface ApolloEnvironmentUrls {
    base: string;
    wsUrl: string;
}

export const ApolloEnvironment = {
    Gcp: {
        base: "https://api-staging-v3.internal-aui.io/ia-controller",
        wsUrl: "wss://api-staging-v3.internal-aui.io",
    },
    Azure: {
        base: "https://azure-staging-v3.aui.io/ia-controller",
        wsUrl: "wss://azure-staging-v3.aui.io",
    },
    Aws: {
        base: "https://aws-staging-v3.aui.io/ia-controller",
        wsUrl: "wss://aws-staging-v3.aui.io",
    },
    // Default points to Gcp for backwards compatibility
    Default: {
        base: "https://api-staging-v3.internal-aui.io/ia-controller",
        wsUrl: "wss://api-staging-v3.internal-aui.io",
    },
} as const;

export type ApolloEnvironment = typeof ApolloEnvironment.Default | typeof ApolloEnvironment.Gcp | typeof ApolloEnvironment.Azure | typeof ApolloEnvironment.Aws;
