// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         organization_id: "organization_id",
 *         user_id: "user_id",
 *         account_id: "account_id",
 *         network_id: "network_id",
 *         page: 1,
 *         limit: 1
 *     }
 */
export interface ControllerApiListUserTasksRequest {
    organization_id: string;
    user_id?: string;
    account_id?: string;
    network_id?: string;
    page?: number;
    limit?: number;
}
