// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "x-aui-user-id": "x-aui-user-id",
 *         "x-aui-source": "x-aui-source",
 *         agent_id: "agent_id",
 *         user_id: "user_id",
 *         task_origin_type: "task_origin_type"
 *     }
 */
export interface CreateTaskRequest {
    "x-aui-user-id"?: string;
    "x-aui-source"?: string;
    /** Agent the task targets. Apollo resolves the network_id (and active version) from agent-settings; the agent's org must match the caller's organization. Replaces the previous network-scope (x-aui-* /network API key) resolution. */
    agent_id: string;
    /** End-user ref id used to attribute the task. Carried in the request body — this is a label, not a security boundary. */
    user_id: string;
    /** RecordOrigin.type value (e.g. web-widget, third-party, stores). */
    task_origin_type: string;
    /** Pin the task to a specific agent version. When omitted, Apollo falls back to the agent's active version. */
    version_id?: string;
    /** Pin the task to an agent version by tag. When omitted, intelligent-agent resolves the tag from the version_id. */
    version_tag?: string;
}
