// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         created_by: "created_by"
 *     }
 */
export interface DirectFollowupSuggestionsRequest {
    context?: Record<string, unknown>;
    created_by: string;
}
