// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "x-aui-end-user-id": "x-aui-end-user-id",
 *         "x-aui-end-user-data": "x-aui-end-user-data",
 *         grant_type: "publishable_key",
 *         publishable_key: "pk_network_..."
 *     }
 */
export interface IssueTokenRequestBody {
    "x-aui-end-user-id"?: string;
    "x-aui-end-user-data"?: string;
    /** Credential grant type. Currently 'publishable_key'. */
    grant_type: string;
    /** Front-end-safe publishable key (pk_network_...). */
    publishable_key: string;
}
