// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         filename: "filename"
 *     }
 */
export interface PresignedUploadRequest {
    /** Original filename, e.g. photo.jpg */
    filename: string;
}
