// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phoneNumber: "phoneNumber",
 *         agentId: "agentId"
 *     }
 */
export interface TextConversationInitiateRequest {
    /** E.164 phone number. */
    phoneNumber: string;
    /** Agent the conversation targets. Apollo resolves the network (and active version) from agent-settings; the agent's organization must match the caller's organization. Mirrors the agent-first contract used by the other APIs (e.g. create-task). */
    agentId: string;
    /** When set, continue this task instead of creating a new one. */
    taskId?: string;
    /** User ref id for a new task; defaults to phone digits. */
    userRefId?: string;
    /** Twilio Content template SID override. */
    templateId?: string;
    /** Bound to template variable {{1}}. */
    agentDisplayName?: string;
    /** Additional template variable overrides ({{2}}, {{3}}, …). */
    contentVariables?: Record<string, string | undefined>;
}
