// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "x-aui-organization-id": "x-aui-organization-id",
 *         "x-aui-user-id": "x-aui-user-id",
 *         "x-aui-source": "x-aui-source",
 *         "x-aui-network-id": "x-aui-network-id",
 *         "x-aui-account-id": "x-aui-account-id",
 *         "x-aui-network-category-id": "x-aui-network-category-id",
 *         caller: "agent_builder",
 *         bundle: {
 *             "key": "value"
 *         }
 *     }
 */
export interface AgentVersionPushRequest {
    "x-aui-organization-id"?: string;
    "x-aui-user-id"?: string;
    "x-aui-source"?: string;
    "x-aui-network-id"?: string;
    "x-aui-account-id"?: string;
    "x-aui-network-category-id"?: string;
    caller: AgentVersionPushRequest.Caller;
    commit_message?: string;
    /** Versioned agent-settings bundle. Must include 'schema_version' and 'general_settings'. */
    bundle: Record<string, unknown>;
}

export namespace AgentVersionPushRequest {
    export const Caller = {
        AgentBuilder: "agent_builder",
        Ui: "ui",
        Cli: "cli",
    } as const;
    export type Caller = (typeof Caller)[keyof typeof Caller];
}
