// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "x-aui-organization-id": "x-aui-organization-id",
 *         "x-aui-user-id": "x-aui-user-id",
 *         "x-aui-source": "x-aui-source",
 *         "x-aui-network-id": "x-aui-network-id",
 *         "x-aui-account-id": "x-aui-account-id",
 *         "x-aui-network-category-id": "x-aui-network-category-id",
 *         source: "version"
 *     }
 */
export interface AgentVersionCreateRequest {
    "x-aui-organization-id"?: string;
    "x-aui-user-id"?: string;
    "x-aui-source"?: string;
    "x-aui-network-id"?: string;
    "x-aui-account-id"?: string;
    "x-aui-network-category-id"?: string;
    source: AgentVersionCreateRequest.Source;
    /** Required when source='version' */
    from_version?: string;
    /** Required when source='template' */
    from_template?: string;
    label?: string;
    tags?: string[];
    notes?: string;
}

export namespace AgentVersionCreateRequest {
    export const Source = {
        Version: "version",
        AgentScope: "agent-scope",
        Template: "template",
        Empty: "empty",
    } as const;
    export type Source = (typeof Source)[keyof typeof Source];
}
